import type { UserProfile, FamilyMember, MedicalRecord, Insight } from '../types';

// ─── Sharma Family Demo Data ──────────────────────────────────

export const demoProfile: UserProfile = {
  id: 'demo-user',
  name: 'Arjun Sharma',
  email: 'arjun.sharma@example.com',
  phone: '+91 98765 43210',
  age: 30,
  gender: 'male',
  photoUrl: null,
  onboardingComplete: true,
  plan: 'free',
  language: 'en',
  createdAt: '2025-10-15T10:00:00Z',
};

export const demoFamilyMembers: FamilyMember[] = [
  {
    id: 'member-self',
    name: 'Arjun Sharma',
    relationship: 'self',
    age: 30,
    gender: 'male',
    conditions: [],
    bloodGroup: 'B+',
    emergencyContact: { name: 'Rajesh Sharma', phone: '+91 98765 11111' },
    doctorName: 'Dr. Vikram Singh',
    doctorPhone: '+91 98765 22222',
    allergies: [],
    createdAt: '2025-10-15T10:00:00Z',
  },
  {
    id: 'member-father',
    name: 'Rajesh Sharma',
    relationship: 'father',
    age: 58,
    gender: 'male',
    conditions: ['Diabetes', 'Hypertension'],
    bloodGroup: 'A+',
    emergencyContact: { name: 'Sunita Sharma', phone: '+91 98765 33333' },
    doctorName: 'Dr. Amit Patel',
    doctorPhone: '+91 98765 44444',
    allergies: ['Sulfa drugs'],
    createdAt: '2025-10-15T10:05:00Z',
  },
  {
    id: 'member-mother',
    name: 'Sunita Sharma',
    relationship: 'mother',
    age: 54,
    gender: 'female',
    conditions: ['Thyroid'],
    bloodGroup: 'O+',
    emergencyContact: { name: 'Rajesh Sharma', phone: '+91 98765 11111' },
    doctorName: 'Dr. Priya Mehta',
    doctorPhone: '+91 98765 55555',
    allergies: [],
    createdAt: '2025-10-15T10:10:00Z',
  },
];

export const demoRecords: MedicalRecord[] = [
  // Rajesh - Diabetes Lab Reports (rising HbA1c trend)
  {
    id: 'rec-1',
    memberId: 'member-father',
    documentType: 'lab_report',
    date: '2025-08-15',
    doctorName: 'Dr. Amit Patel',
    hospitalName: 'Apollo Diagnostics',
    patientName: 'Rajesh Sharma',
    diagnosis: ['Type 2 Diabetes Mellitus'],
    medicines: [],
    labResults: [
      { testName: 'HbA1c', value: '6.8', unit: '%', referenceRange: '4.0-5.6', status: 'high' },
      { testName: 'Fasting Glucose', value: '132', unit: 'mg/dL', referenceRange: '70-100', status: 'high' },
      { testName: 'Post-Prandial Glucose', value: '198', unit: 'mg/dL', referenceRange: '70-140', status: 'high' },
    ],
    keyFindings: 'HbA1c at 6.8% indicates pre-diabetic to early diabetic range. Fasting and post-prandial glucose elevated.',
    followUpDate: '2025-11-15',
    language: 'English',
    uploadedImageUrl: '',
    createdAt: '2025-08-15T14:00:00Z',
    updatedAt: '2025-08-15T14:00:00Z',
  },
  {
    id: 'rec-2',
    memberId: 'member-father',
    documentType: 'lab_report',
    date: '2025-11-20',
    doctorName: 'Dr. Amit Patel',
    hospitalName: 'Apollo Diagnostics',
    patientName: 'Rajesh Sharma',
    diagnosis: ['Type 2 Diabetes Mellitus'],
    medicines: [],
    labResults: [
      { testName: 'HbA1c', value: '7.2', unit: '%', referenceRange: '4.0-5.6', status: 'high' },
      { testName: 'Fasting Glucose', value: '145', unit: 'mg/dL', referenceRange: '70-100', status: 'high' },
      { testName: 'Post-Prandial Glucose', value: '215', unit: 'mg/dL', referenceRange: '70-140', status: 'high' },
    ],
    keyFindings: 'HbA1c has risen from 6.8% to 7.2%. Blood sugar control appears to be worsening. Medication review recommended.',
    followUpDate: '2026-02-20',
    language: 'English',
    uploadedImageUrl: '',
    createdAt: '2025-11-20T14:00:00Z',
    updatedAt: '2025-11-20T14:00:00Z',
  },
  {
    id: 'rec-3',
    memberId: 'member-father',
    documentType: 'lab_report',
    date: '2026-03-10',
    doctorName: 'Dr. Amit Patel',
    hospitalName: 'Apollo Diagnostics',
    patientName: 'Rajesh Sharma',
    diagnosis: ['Type 2 Diabetes Mellitus'],
    medicines: [],
    labResults: [
      { testName: 'HbA1c', value: '7.8', unit: '%', referenceRange: '4.0-5.6', status: 'high' },
      { testName: 'Fasting Glucose', value: '158', unit: 'mg/dL', referenceRange: '70-100', status: 'high' },
      { testName: 'Post-Prandial Glucose', value: '242', unit: 'mg/dL', referenceRange: '70-140', status: 'high' },
    ],
    keyFindings: 'HbA1c has risen to 7.8% — a concerning upward trend over 3 consecutive tests. Urgent review of diabetes management needed.',
    followUpDate: '2026-04-10',
    language: 'English',
    uploadedImageUrl: '',
    createdAt: '2026-03-10T14:00:00Z',
    updatedAt: '2026-03-10T14:00:00Z',
  },
  // Rajesh - BP Medicine Prescription
  {
    id: 'rec-4',
    memberId: 'member-father',
    documentType: 'prescription',
    date: '2026-03-10',
    doctorName: 'Dr. Amit Patel',
    hospitalName: 'City Medical Center',
    patientName: 'Rajesh Sharma',
    diagnosis: ['Essential Hypertension', 'Type 2 Diabetes Mellitus'],
    medicines: [
      { name: 'Amlodipine', dosage: '5mg', frequency: 'Once daily (morning)', duration: '90 days', estimatedRunoutDate: '2026-06-08' },
      { name: 'Metformin', dosage: '500mg', frequency: 'Twice daily', duration: '90 days', estimatedRunoutDate: '2026-06-08' },
      { name: 'Telmisartan', dosage: '40mg', frequency: 'Once daily', duration: '90 days', estimatedRunoutDate: '2026-06-08' },
      { name: 'Atorvastatin', dosage: '10mg', frequency: 'Once daily (night)', duration: '90 days', estimatedRunoutDate: '2026-06-08' },
    ],
    labResults: [],
    keyFindings: 'Prescription for hypertension and diabetes management. BP was 148/92 mmHg at visit. Four medications prescribed for 3½ months.',
    followUpDate: '2026-06-10',
    language: 'English',
    uploadedImageUrl: '',
    createdAt: '2026-03-10T15:00:00Z',
    updatedAt: '2026-03-10T15:00:00Z',
  },
  // Rajesh - Kidney Function Test
  {
    id: 'rec-5',
    memberId: 'member-father',
    documentType: 'lab_report',
    date: '2026-03-10',
    doctorName: 'Dr. Amit Patel',
    hospitalName: 'Apollo Diagnostics',
    patientName: 'Rajesh Sharma',
    diagnosis: [],
    medicines: [],
    labResults: [
      { testName: 'Creatinine', value: '1.4', unit: 'mg/dL', referenceRange: '0.7-1.2', status: 'high' },
      { testName: 'BUN', value: '22', unit: 'mg/dL', referenceRange: '7-20', status: 'high' },
      { testName: 'eGFR', value: '62', unit: 'mL/min', referenceRange: '>90', status: 'low' },
      { testName: 'Uric Acid', value: '7.1', unit: 'mg/dL', referenceRange: '3.5-7.2', status: 'normal' },
    ],
    keyFindings: 'Creatinine slightly elevated at 1.4 mg/dL (normal: 0.7-1.2). eGFR at 62 suggests mildly reduced kidney function. Needs monitoring.',
    followUpDate: '2026-06-10',
    language: 'English',
    uploadedImageUrl: '',
    createdAt: '2026-03-10T14:30:00Z',
    updatedAt: '2026-03-10T14:30:00Z',
  },
  // Rajesh - General Health Checkup
  {
    id: 'rec-6',
    memberId: 'member-father',
    documentType: 'lab_report',
    date: '2026-04-05',
    doctorName: 'Dr. Amit Patel',
    hospitalName: 'LifeCare Diagnostics',
    patientName: 'Rajesh Sharma',
    diagnosis: [],
    medicines: [],
    labResults: [
      { testName: 'Total Cholesterol', value: '195', unit: 'mg/dL', referenceRange: '<200', status: 'normal' },
      { testName: 'HDL Cholesterol', value: '42', unit: 'mg/dL', referenceRange: '>40', status: 'normal' },
      { testName: 'LDL Cholesterol', value: '118', unit: 'mg/dL', referenceRange: '<100', status: 'high' },
      { testName: 'Triglycerides', value: '175', unit: 'mg/dL', referenceRange: '<150', status: 'high' },
      { testName: 'Blood Pressure', value: '138/88', unit: 'mmHg', referenceRange: '<120/80', status: 'high' },
    ],
    keyFindings: 'Lipid profile shows elevated LDL and triglycerides. BP controlled better on current medication but still above target.',
    followUpDate: null,
    language: 'English',
    uploadedImageUrl: '',
    createdAt: '2026-04-05T10:00:00Z',
    updatedAt: '2026-04-05T10:00:00Z',
  },
  // Sunita - Thyroid Report
  {
    id: 'rec-7',
    memberId: 'member-mother',
    documentType: 'lab_report',
    date: '2026-03-20',
    doctorName: 'Dr. Priya Mehta',
    hospitalName: 'Metropolis Lab',
    patientName: 'Sunita Sharma',
    diagnosis: ['Hypothyroidism'],
    medicines: [],
    labResults: [
      { testName: 'TSH', value: '5.8', unit: 'mIU/L', referenceRange: '0.4-4.0', status: 'high' },
      { testName: 'T3', value: '1.1', unit: 'ng/mL', referenceRange: '0.8-2.0', status: 'normal' },
      { testName: 'T4', value: '6.2', unit: 'µg/dL', referenceRange: '5.1-14.1', status: 'normal' },
    ],
    keyFindings: 'TSH elevated at 5.8 — indicates subclinical hypothyroidism. T3 and T4 within normal range. May need medication adjustment.',
    followUpDate: '2026-06-20',
    language: 'English',
    uploadedImageUrl: '',
    createdAt: '2026-03-20T11:00:00Z',
    updatedAt: '2026-03-20T11:00:00Z',
  },
  // Sunita - Thyroid Prescription
  {
    id: 'rec-8',
    memberId: 'member-mother',
    documentType: 'prescription',
    date: '2026-03-20',
    doctorName: 'Dr. Priya Mehta',
    hospitalName: 'City Medical Center',
    patientName: 'Sunita Sharma',
    diagnosis: ['Hypothyroidism'],
    medicines: [
      { name: 'Levothyroxine', dosage: '50mcg', frequency: 'Once daily (empty stomach, morning)', duration: '90 days', estimatedRunoutDate: '2026-06-18' },
      { name: 'Calcium + Vitamin D3', dosage: '500mg + 250IU', frequency: 'Once daily (after lunch)', duration: '90 days', estimatedRunoutDate: '2026-06-18' },
    ],
    labResults: [],
    keyFindings: 'Thyroid medication prescription renewed. Levothyroxine dose maintained at 50mcg. Calcium supplementation added.',
    followUpDate: '2026-06-20',
    language: 'English',
    uploadedImageUrl: '',
    createdAt: '2026-03-20T12:00:00Z',
    updatedAt: '2026-03-20T12:00:00Z',
  },
];

export const demoInsights: Insight[] = [
  {
    id: 'insight-1',
    memberId: 'member-father',
    type: 'urgent',
    title: 'HbA1c Rising — 3 Consecutive Tests',
    message: 'Rajesh\'s HbA1c has risen from 6.8% to 7.2% to 7.8% over the last 7 months. This is a concerning trend that needs immediate medical attention.',
    actionRequired: 'Schedule an appointment with Dr. Amit Patel to review diabetes management plan.',
    relatedTests: ['HbA1c', 'Fasting Glucose', 'Post-Prandial Glucose'],
    priority: 1,
    isRead: false,
    generatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'insight-2',
    memberId: 'member-father',
    type: 'warning',
    title: 'Kidney Function Needs Monitoring',
    message: 'Creatinine is slightly elevated at 1.4 mg/dL and eGFR at 62 suggests mildly reduced kidney function. This may be related to long-term diabetes and hypertension.',
    actionRequired: 'Discuss kidney function monitoring with your doctor at the next visit.',
    relatedTests: ['Creatinine', 'eGFR', 'BUN'],
    priority: 2,
    isRead: false,
    generatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'insight-3',
    memberId: 'member-father',
    type: 'positive',
    title: 'Blood Pressure Improving',
    message: 'Blood pressure has improved from 148/92 to 138/88 mmHg since starting the current medication. The treatment appears to be working, though still slightly above target.',
    actionRequired: null,
    relatedTests: ['Blood Pressure'],
    priority: 4,
    isRead: false,
    generatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'insight-4',
    memberId: 'member-father',
    type: 'reminder',
    title: 'Follow-up Appointment Due',
    message: 'Your follow-up appointment with Dr. Amit Patel was scheduled for April 10, 2026. Please reschedule if not yet done.',
    actionRequired: 'Call Dr. Patel\'s clinic to reschedule the follow-up appointment.',
    relatedTests: [],
    priority: 3,
    isRead: true,
    generatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'insight-5',
    memberId: 'member-mother',
    type: 'warning',
    title: 'TSH Slightly Elevated',
    message: 'Sunita\'s TSH is 5.8 mIU/L (normal: 0.4-4.0). This indicates subclinical hypothyroidism. Current medication dosage may need adjustment.',
    actionRequired: 'Discuss TSH levels with Dr. Priya Mehta at the next visit.',
    relatedTests: ['TSH'],
    priority: 3,
    isRead: false,
    generatedAt: '2026-04-10T10:00:00Z',
  },
];

// Helper to get demo data
export function getDemoData() {
  return {
    profile: demoProfile,
    familyMembers: demoFamilyMembers,
    records: demoRecords,
    insights: demoInsights,
  };
}
