import { useApp } from '../context/AppContext';
import { useState, useRef } from 'react';
import { ClipboardList, Loader2, Copy, Share2, Printer, Download } from 'lucide-react';
import type { DoctorSummary } from '../types';
import { getStatusColor, getInitials } from '../utils/helpers';
import { generateDoctorSummaryAI } from '../services/ai';

export default function SummaryPage() {
  const { familyMembers, selectedMemberId, setSelectedMemberId, getMemberRecords, getSelectedMember, getMemberMedicines } = useApp();
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<DoctorSummary | null>(null);
  const summaryRef = useRef<HTMLDivElement>(null);

  const member = getSelectedMember();
  const records = getMemberRecords(selectedMemberId);
  const meds = getMemberMedicines(selectedMemberId);

  const generateSummary = async () => {
    if (!member) return;
    setLoading(true);

    try {
      const generatedSummary = await generateDoctorSummaryAI(member, records, meds);
      setSummary(generatedSummary);
    } catch (err) {
      console.error('Summary generation failed:', err);
    }

    setLoading(false);
  };

  const handleShare = (method: 'copy' | 'whatsapp' | 'print' | 'pdf') => {
    if (!summary) return;
    const text = `DOCTOR VISIT SUMMARY\n${summary.patientInfo.name}, ${summary.patientInfo.age}yrs, ${summary.patientInfo.gender}\nBlood Group: ${summary.patientInfo.bloodGroup}\n\nConditions: ${summary.activeConditions.join(', ')}\nMedicines: ${summary.currentMedicines.map(m => `${m.name} ${m.dosage}`).join(', ')}\nAllergies: ${summary.allergies.join(', ') || 'None'}\n\nRecent Labs:\n${summary.recentLabHighlights.map(l => `- ${l.test}: ${l.value} (${l.status})`).join('\n')}\n\nHistory:\n${summary.keyHistoryPoints.map(p => `- ${p}`).join('\n')}\n\nQuestions:\n${summary.questionsForDoctor.map(q => `- ${q}`).join('\n')}\n\nGenerated by MediMem on ${summary.generatedDate}`;

    if (method === 'copy') {
      navigator.clipboard.writeText(text);
      alert('Copied to clipboard!');
    } else if (method === 'whatsapp') {
      window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
    } else if (method === 'print') {
      window.print();
    } else if (method === 'pdf') {
      // Use html2pdf.js
      import('html2pdf.js').then(({ default: html2pdf }) => {
        if (summaryRef.current) {
          html2pdf()
            .set({
              margin: 10,
              filename: `${summary.patientInfo.name.replace(/\s+/g, '_')}_Summary.pdf`,
              html2canvas: { scale: 2 },
              jsPDF: { format: 'a4', orientation: 'portrait' },
            })
            .from(summaryRef.current)
            .save();
        }
      }).catch(err => {
        console.warn('html2pdf not available:', err);
        // Fallback to print
        window.print();
      });
    }
  };

  return (
    <div className="pb-4">
      {/* Header */}
      <div className="px-4 pt-2 pb-3">
        <h1 className="text-xl font-bold text-gray-900 flex items-center gap-2">
          <ClipboardList size={20} className="text-blue-500" /> Pre-Visit Summary
        </h1>
        <p className="text-sm text-gray-500 mt-0.5">Generate a doctor-ready health summary</p>
      </div>

      {/* Member Selector */}
      <div className="px-4 pb-4">
        <div className="flex gap-2 overflow-x-auto pb-1" style={{ scrollbarWidth: 'none' }}>
          {familyMembers.map(m => (
            <button
              key={m.id}
              onClick={() => { setSelectedMemberId(m.id); setSummary(null); }}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium flex-shrink-0 transition-colors ${
                selectedMemberId === m.id ? 'bg-blue-100 text-blue-700 ring-1 ring-blue-300' : 'bg-gray-50 text-gray-500'
              }`}
            >
              <span className={`w-5 h-5 rounded-full text-[9px] font-bold flex items-center justify-center ${
                selectedMemberId === m.id ? 'bg-blue-600 text-white' : 'bg-gray-200'
              }`}>
                {getInitials(m.name).charAt(0)}
              </span>
              {m.name.split(' ')[0]}
            </button>
          ))}
        </div>
      </div>

      {!summary && !loading && (
        <div className="px-4">
          <div className="bg-blue-50 rounded-2xl p-8 text-center">
            <div className="w-16 h-16 bg-blue-100 rounded-full mx-auto mb-4 flex items-center justify-center">
              <ClipboardList size={28} className="text-blue-600" />
            </div>
            <h3 className="font-semibold text-gray-900 mb-1">Ready to generate</h3>
            <p className="text-sm text-gray-500 mb-2">
              AI will create a 1-page summary of {member?.name}'s health for your doctor
            </p>
            {records.length === 0 && (
              <p className="text-xs text-orange-600 mb-3">⚠ No records found. Add some records first for a detailed summary.</p>
            )}
            <button
              onClick={generateSummary}
              className="bg-teal-600 text-white px-8 py-3 rounded-xl font-semibold hover:bg-teal-700 transition-colors shadow-sm shadow-teal-200"
            >
              ✨ Generate Summary
            </button>
          </div>
        </div>
      )}

      {loading && (
        <div className="px-4 py-16 text-center">
          <Loader2 size={32} className="animate-spin text-teal-600 mx-auto mb-4" />
          <p className="font-semibold text-gray-900">Generating summary...</p>
          <p className="text-sm text-gray-500">Analyzing {records.length} records for {member?.name}</p>
        </div>
      )}

      {/* Summary Display */}
      {summary && !loading && (
        <>
          <div className="mx-4 print-only" id="doctor-summary" ref={summaryRef}>
            <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
              {/* Summary Header */}
              <div className="bg-teal-600 text-white px-5 py-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-lg font-bold">{summary.patientInfo.name}</h2>
                    <p className="text-sm text-teal-100">Doctor Visit Summary</p>
                  </div>
                  <p className="text-xs text-teal-200">{summary.generatedDate}</p>
                </div>
              </div>

              <div className="p-5 space-y-5">
                {/* Patient Info */}
                <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">
                  <div><span className="text-gray-400 text-xs">Age</span><p className="font-medium">{summary.patientInfo.age} years</p></div>
                  <div><span className="text-gray-400 text-xs">Gender</span><p className="font-medium">{summary.patientInfo.gender}</p></div>
                  <div><span className="text-gray-400 text-xs">Blood Group</span><p className="font-medium">{summary.patientInfo.bloodGroup}</p></div>
                  <div><span className="text-gray-400 text-xs">Allergies</span><p className="font-medium">{summary.allergies.length > 0 ? summary.allergies.join(', ') : 'None known'}</p></div>
                </div>

                <hr className="border-gray-100" />

                {/* Conditions */}
                <div>
                  <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Active Conditions</h3>
                  <div className="flex flex-wrap gap-1.5">
                    {summary.activeConditions.length > 0 ? summary.activeConditions.map(c => (
                      <span key={c} className="px-2.5 py-1 bg-red-50 text-red-700 text-xs font-semibold rounded-full">{c}</span>
                    )) : <span className="text-sm text-gray-400">None</span>}
                  </div>
                </div>

                <hr className="border-gray-100" />

                {/* Medicines */}
                <div>
                  <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Current Medicines</h3>
                  {summary.currentMedicines.length > 0 ? (
                    <div className="text-sm space-y-1">
                      {summary.currentMedicines.map((m, i) => (
                        <div key={i} className="flex items-center justify-between py-1.5 border-b border-gray-50 last:border-0">
                          <span className="font-medium text-gray-900">{m.name}</span>
                          <span className="text-gray-500">{m.dosage} • {m.frequency}</span>
                        </div>
                      ))}
                    </div>
                  ) : <p className="text-sm text-gray-400">No current medications</p>}
                </div>

                <hr className="border-gray-100" />

                {/* Lab Highlights */}
                <div>
                  <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Recent Lab Highlights</h3>
                  {summary.recentLabHighlights.length > 0 ? (
                    <div className="space-y-1">
                      {summary.recentLabHighlights.map((l, i) => (
                        <div key={i} className="flex items-center justify-between text-sm py-1.5 border-b border-gray-50 last:border-0">
                          <span className="text-gray-700">{l.test}</span>
                          <div className="flex items-center gap-2">
                            <span className="font-medium">{l.value}</span>
                            <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded-full ${getStatusColor(l.status)}`}>
                              {l.status.toUpperCase()}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : <p className="text-sm text-gray-400">No recent lab results</p>}
                </div>

                <hr className="border-gray-100" />

                {/* History */}
                <div>
                  <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Key Medical History</h3>
                  <ul className="space-y-1">
                    {summary.keyHistoryPoints.map((p, i) => (
                      <li key={i} className="text-sm text-gray-700 flex items-start gap-2">
                        <span className="text-gray-400 mt-0.5">•</span> {p}
                      </li>
                    ))}
                  </ul>
                </div>

                <hr className="border-gray-100" />

                {/* Questions for Doctor */}
                <div>
                  <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Suggested Questions for Doctor</h3>
                  <ul className="space-y-1">
                    {summary.questionsForDoctor.map((q, i) => (
                      <li key={i} className="text-sm text-teal-700 italic flex items-start gap-2">
                        <span className="text-teal-400 mt-0.5">?</span> {q}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Footer */}
              <div className="bg-gray-50 px-5 py-3 text-center border-t border-gray-100">
                <p className="text-[10px] text-gray-400">Generated by MediMem • {summary.generatedDate}</p>
              </div>
            </div>
          </div>

          {/* Share Actions */}
          <div className="px-4 mt-4 grid grid-cols-2 gap-2 no-print">
            <button onClick={() => handleShare('copy')} className="bg-gray-50 py-2.5 rounded-xl text-sm font-medium text-gray-700 hover:bg-gray-100 transition-colors flex items-center justify-center gap-1.5">
              <Copy size={14} /> Copy
            </button>
            <button onClick={() => handleShare('whatsapp')} className="bg-green-50 py-2.5 rounded-xl text-sm font-medium text-green-700 hover:bg-green-100 transition-colors flex items-center justify-center gap-1.5">
              <Share2 size={14} /> WhatsApp
            </button>
            <button onClick={() => handleShare('print')} className="bg-blue-50 py-2.5 rounded-xl text-sm font-medium text-blue-700 hover:bg-blue-100 transition-colors flex items-center justify-center gap-1.5">
              <Printer size={14} /> Print
            </button>
            <button onClick={() => handleShare('pdf')} className="bg-purple-50 py-2.5 rounded-xl text-sm font-medium text-purple-700 hover:bg-purple-100 transition-colors flex items-center justify-center gap-1.5">
              <Download size={14} /> Save PDF
            </button>
            <button onClick={generateSummary} className="col-span-2 bg-teal-50 py-2.5 rounded-xl text-sm font-medium text-teal-700 hover:bg-teal-100 transition-colors flex items-center justify-center gap-1.5">
              ✨ Regenerate
            </button>
          </div>
        </>
      )}
    </div>
  );
}
